#!/usr/bin/env bash
set -e

TEST_ENV="$1"
TEST_CONFIG="$2"
BINARY=/tests/firefox-nightly/firefox
#CONFIG_FILE=/tests/venv/config.json
CONFIG_FILE=/tests/config.json

#chmod 777 $CONFIG_FILE
echo $TEST_CONFIG > $CONFIG_FILE

if [ "$TEST_ENV" == "prod" ] && [ -z "$TESTFILE" ]; then
  TESTFILE="test_sync.js"
fi

if [ ! -z "$TESTFILE" ]; then
  TESTFILE_ARGS="--testfile='$TESTFILE'"
fi

if [ "$TEST_ENV" == "prod" ] || [ "$TEST_ENV" == "stage" ]; then
  MOZ_HEADLESS=1 /tests/venv/bin/runtps --debug --binary="$BINARY" --configfile="$CONFIG_FILE" $TESTFILE_ARGS
else
  echo "Unknown environment: $TEST_ENV --> ABORTING!"
  exit 127
fi
